In [1]:
import tensorflow as tf
import numpy as np


In [2]:
# how this workstf.reduce_sum()

x = np.array([[1,1,1],[1,1,1]])
sess = tf.Session()
sess.run(tf.reduce_sum(x))


6

In [3]:
sess.run(tf.reduce_sum(x,0))

array([2, 2, 2])

In [4]:
sess.run(tf.reduce_sum(x,1))

array([3, 3])

In [5]:
y = np.ones((3,3))

In [6]:
y

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
sess.run(tf.reduce_sum(y))

9.0

In [8]:
sess.run(tf.reduce_sum(y,0))

array([ 3.,  3.,  3.])

In [10]:
sess.run(tf.reduce_sum(y,1))

array([ 3.,  3.,  3.])

## An  complete graph example with Tensorboard

In [13]:
a = tf.constant(5, name="input_a")
b = tf.constant(3, name="input_b")
c = tf.multiply(a,b, name="mul_c")
d = tf.add(a,b, name="add_d")
e = tf.add(c,d, name="add_e")


In [27]:
sess = tf.Session()
output = sess.run(e)
print(output)

23


In [28]:
# Lets visualize the Data by using Tensorboard
#this "my_graph" dir will be created in your current code/project directory
# execute this command  < tensorboard --logdir="my_graph" >   on your terminal -> copy the url & paste in browers,

writer = tf.summary.FileWriter('./my_graph', sess.graph)
print(sess.run(e))
writer.close()
sess.close()

23
