In [7]:
import tensorflow as tf
import numpy as np


In [30]:
# how this workstf.reduce_sum()

x = np.array([[1,1,1],[1,1,1]])
sess = tf.Session()
sess.run(tf.reduce_sum(x))


6

In [31]:
sess.run(tf.reduce_sum(x,0))

array([2, 2, 2])

In [32]:
sess.run(tf.reduce_sum(x,1))

array([3, 3])

In [37]:
y = np.ones((3,3))

In [39]:
y

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [42]:
sess.run(tf.reduce_sum(y))

9.0

In [44]:
sess.run(tf.reduce_sum(y,0))

array([ 3.,  3.,  3.])

In [45]:
sess.run(tf.reduce_sum(y,1))

array([ 3.,  3.,  3.])